First=("Summer")
Second=("Spring")
Third=("Winter")
Fourth=("Fall")  
print("Enter the First Season:",First)
print("Enter the Second Season:",Second)
print("Enter the Third Season:",Third)
print("Enter the Fourth Season:",Fourth)
print("You Have ENTERED the following season and those are", First,",",Second,",",Third,"and",Fourth)